[package]
name = "s3-file-upload"
version = "0.1.0"
authors = ["Steven Thompson <contact@stevenjt.com>"]

[dependencies]
rusoto = {version = "0.24.0", features = ["s3"]}
rust-crypto = "^0.2"
term-painter = "0.2"